plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.7"
}

group = "back"
version = "1.0.0"

java.sourceCompatibility = JavaVersion.VERSION_21
java.targetCompatibility = JavaVersion.VERSION_21

repositories {
    mavenCentral()
    maven("https://jitpack.io")
}

dependencies {
    // PowerNukkitX API — local JAR generated by: cd ../PowerNukkitX && gradlew shadowJar
    // Requires Java 21. Once compiled, the JAR appears at the path below.
    compileOnly(files("../PowerNukkitX/build/powernukkitx.jar"))

    // JetBrains annotations (@Nullable, @NotNull) — used in the API
    compileOnly("org.jetbrains:annotations:24.1.0")
}

tasks.withType<JavaCompile> {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    archiveClassifier.set("")
    archiveFileName.set("InvMenuPNX-${project.version}.jar")
}

tasks.build {
    dependsOn(tasks.shadowJar)
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            groupId = "com.github.zorao"
            artifactId = "InvMenuPNX"
            version = project.version.toString()
        }
    }
}
